name = "aviationpedia-live"
main = "worker.js"
compatibility_date = "2025-01-01"

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "FLIGHTS"
id = "e0873a24b32f4a9b9038f72c575b1bab"

[[kv_namespaces]]
binding = "LOOKUP"
id = "844799a0299b462aa45c116e40f4dc75"

[vars]
API_TOKEN = "REPLACE_ME"
