/** Data model for the encyclopedia dataset (generated by data/pipeline). */

export interface Aircraft {
  id: string
  en: string
  zh: string | null
  desc: string | null
  manufacturer: string | null // manufacturer QID
  lengthM: number | null
  wingspanM: number | null
  heightM: number | null
  widthM: number | null
  rangeKm: number | null
  speedKmh: number | null
  wingAreaM2: number | null
  capacity: number | null
  produced: number | null
  altitudeM: number | null
  firstFlight: string | null
  serviceEntry: string | null
  images: string[]
  variants: string[] // child aircraft QIDs
  poweredBy: string[] // engine QIDs
  operators: string[] // airline QIDs
  family: string | null // parent family QID (for variants)
  basedOn: string[] // derivative-of aircraft QIDs (P144)
  massKg: number | null
}

export interface Airline {
  id: string
  en: string
  zh: string | null
  desc: string | null
  iata: string | null
  icao: string | null
  callsign: string | null
  country: string | null // country QID
  hq: string | null // HQ QID
  hubs: string[] // airport QIDs
  founded: string | null
  website: string | null
  logo: string | null
  image: string | null
  fleet: string[] // aircraft QIDs
  alliance: string | null // alliance QID
  active: boolean
  source: 'wikidata' | 'openflights'
}

export interface Alliance {
  id: string
  en: string
  zh?: string
  founded?: string
  website?: string
  logo?: string
  image?: string
  members?: number
}

export interface Manufacturer {
  id: string
  en: string
  zh: string | null
  aircraftCount: number
}

export interface AircraftCode {
  name: string
  iata: string
  icao: string
}

export interface Encyclopedia {
  generatedAt: string
  meta: {
    aircraftCount: number
    airlineCount: number
    allianceCount: number
    manufacturerCount: number
  }
  aircraft: Aircraft[]
  airlines: Airline[]
  alliances: Alliance[]
  allianceMembers: Record<string, (string | null)[]>
  manufacturers: Manufacturer[]
  aircraftCodes: AircraftCode[]
  labels: {
    refs: Record<string, [string, string | null]> // hub/country/hq QID -> [en, zh]
    ext: Record<string, [string, string | null]> // variants/engines QID -> [en, zh]
    mfr: Record<string, [string, string | null]>
  }
}

export type EntityKind = 'aircraft' | 'airline'
